blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog_app.forms import *
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('b/', include('blog_app.urls')),
    path('u/', include('authorisation.urls')),
    path('', home),
]

blog/blog_app/urls.py
# IMPORTS
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    # path('', views.home),
    # path('b/comment/<str:blog_title>', views.comment),
    path('create_blog', views.create_blog),
    path('update_blog/<str:title>', views.update_blog),
    path('<str:blog_title>', views.blog),
    # path('u/create_user', views.create_user),
    # path('u/login_user', views.login_user),
    # path('u/logout_user', views.logout_user),
]

blog/blog_app/models.py
from django.db import models

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    content = models.TextField()
    facebook = models.CharField(max_length=100, null=True, blank=True)
    twitter = models.CharField(max_length=30, null=True, blank=True)
    github = models.CharField(max_length=60, null=True, blank=True)
    linkedin = models.CharField(max_length=60, null=True, blank=True)
    personal_website = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name

class BlogPostComment(models.Model):
    comment = models.TextField()

    def __str__(self):
        return self.comment

class BlogPost(models.Model):
    id = models.BigIntegerField(primary_key=True, unique=True)
    image = models.ImageField()
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    # author = models.CharField(max_length=50)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)
    content = models.TextField()
    published = models.BooleanField(null=False, blank=False)
    # team = models.ManyToManyField(Author)
    whatsapp_message = models.CharField(max_length=1000,null=True)
    facebook_link = models.CharField(max_length=100,null=True)
    comments = models.ManyToManyField(BlogPostComment,blank=True)
    # TODO : ADD COMMENTS
    # TODO : ADD FEEDBACK
    feedback_upvote = models.IntegerField(default=0)
    feedback_loved = models.IntegerField(default=0)
    feedback_amazed = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class EmailIPLocator(models.Model):
    email = models.EmailField()
    city = models.TextField
    country = models.TextField
    asname = models.TextField
    isp = models.TextField
    lat = models.FloatField()
    lon = models.FloatField()
    ip = models.IPAddressField
    zip_code = models.IntegerField()
    
    def __str__(self):
        return self.email

blog/blog_app/forms.py
from django.forms import ModelForm
from .models import BlogPost
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class BlogPostForm(ModelForm):
    class Meta:
        model = BlogPost
        fields = ['id','image','title','description','author','content']

class EditorBlogPostForm(ModelForm):
    class Meta:
        model = BlogPost
        fields = '__all__'

class FeedbackForm(ModelForm):
    class Meta:
        model = BlogPost
        fields = ['feedback_upvote','feedback_loved','feedback_amazed']

blog/blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from json import dumps
from django.contrib.auth.decorators import login_required
from blog_app.forms import *
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def home(req):
    blogs = BlogPost.objects.all()
    data = {
        'title': "Home",
        'blog': "thePythoneer.tech",
        'blogs': blogs,
        'authenticated' : req.user.is_authenticated
    }
    return render(req, 'home.html', data)

blog/blog_app/views.py
from django.shortcuts import render
import uuid
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from .models import BlogPost
from authorisation.decorators import *
from .forms import *

def uniqueidgenerator():
    x = uuid.uuid4().int >> 64
    if x < 9223372036854775807:
        return x
    else:
        return uniqueidgenerator()

# Create your views here.
# # # # # # # # # # # # # # # # # # # # #    BLOG SECTION    # # # # # # # # # # # # # # # # # # # # # 
# api => "/b/<str:blog_title>"
# request => GET, POST
# returns => blog post with title = blog_title
def blog(req,blog_title):
    if blog_title == 'dashboard':
        return dashboard(req)
    blog = BlogPost.objects.filter(title=blog_title)[0]
    tags = blog.tags.all()
    feedback_form = FeedbackForm(instance=blog)
    if req.method == 'POST':
        
        blog = BlogPost.objects.filter(title=blog_title)[0]
        blog.feedback_amazed += int(req.POST['feedback_amazed'])
        blog.feedback_loved += int(req.POST["feedback_loved"])
        blog.feedback_upvote += int(req.POST['feedback_upvote'])
        blog.save()
        res = {
            'feedback_amazed': blog.feedback_amazed,
            'feedback_loved': blog.feedback_loved,
            'feedback_upvote': blog.feedback_upvote,
        }
        return JsonResponse(res)
    return render(req, 'blog.html',{'title': blog.title,'blog': "thePythonner.tech",'post': blog,'tags': tags, 'feedback_form': feedback_form, 'authenticated': req.user.is_authenticated})


# api => "/b/create_blog"
# request => GET, POST
# returns => Create a new Blog POST
@login_required(login_url="/u/login_user")
@allowed_user(allowed_roles=['Editor'])
def create_blog(req):
    form = BlogPostForm(initial={'id': uniqueidgenerator()})
    context = {
        'form': form
    }
    if req.method == 'POST':
        form = BlogPostForm(req.POST, req.FILES)
        if form.is_valid():
            form.save()
            return redirect("/")
    return render(req, 'create_blog.html',{'title': "Create Blog Post",'blog': "thePythonner.tech", 'form': form, 'authenticated': req.user.is_authenticated})


# api => "/b/dashboard"
# request => GET, POST
# returns => Editor Dashboard
# @login_required(login_url="/u/login_user")
# @allowed_user(allowed_roles=['Editor'])
def dashboard(req):
    return render(req, 'dashboard.html')


# api => "/b/update_blog/<str:title>"
# request => GET, POST
# returns => Update Blog POST
@login_required(login_url="/")
@allowed_user(allowed_roles=['Editor'])
def update_blog(req, title):
    blog = BlogPost.objects.filter(title=title)[0]
    form = BlogPostForm(instance=blog)
    context = {
        'form': form
    }
    if req.method == 'POST':
        form = BlogPostForm(req.POST, req.FILES, instance=blog)
        if form.is_valid():
            form.save()
            return redirect("/")
    return render(req, 'create_blog.html',{'title': "Create Blog Post",'blog': "thePythonner.tech", 'form': form,  'authenticated': req.user.is_authenticated})

blog/blog_app/templates/create_blog.html
{% extends "basic_layout.html" %}
{% load static %}
{% block content %}
<style>
  #id_id {
    display: none;
  }
  label[for=id_id] {
    display: none;
  }
</style>
<script src="https://cdn.tiny.cloud/1/glkkmvfr6amtkidkd2qdb4pmrkf9wlomwmsaegunkc8az915/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>

var useDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches;

tinymce.init({
  selector: 'textarea#id_content',
  setup: function (editor) {
        editor.on('change', function () {
            editor.save();
        });
    },
  plugins: 'print visualblocks checklist preview paste importcss searchreplace autolink autosave save directionality code visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount imagetools textpattern noneditable help charmap quickbars emoticons',
  imagetools_cors_hosts: ['picsum.photos'],
  menubar: 'file edit view insert format tools table help',
  toolbar: 'undo redo | bold italic underline strikethrough superscript subscript | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media template link anchor codesample | ltr rtl',
  toolbar_sticky: true,
  autosave_ask_before_unload: true,
  autosave_interval: '30s',
  autosave_prefix: '{path}{query}-{id}-',
  autosave_restore_when_empty: false,
  autosave_retention: '2m',
  image_advtab: true,
  importcss_append: true,
  height: 600,
  menu: {
    format: {
      title: 'Format',
      items: 'bold italic underline strikethrough superscript subscript codeformat | checklist | formats blockformats fontformats fontsizes align | forecolor backcolor | removeformat'
    }
  },
  image_caption: true,
  quickbars_insert_toolbar: 'anchor quickimage quicktable media link',
  quickbars_selection_toolbar: 'bold italic underline | quicklink h1 h2 h3 blockquote quickimage quicktable',
  noneditable_noneditable_class: 'mceNonEditable',
  toolbar_mode: 'sliding',
  contextmenu: 'link image imagetools table',
  skin: useDarkMode ? 'oxide-dark' : 'oxide',
  content_css: useDarkMode ? 'dark' : 'default',
  content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }',
  style_formats: [
    { title: 'Headers', items: [
      { title: 'h1', block: 'h1' },
      { title: 'h2', block: 'h2' },
      { title: 'h3', block: 'h3' },
      { title: 'h4', block: 'h4' },
      { title: 'h5', block: 'h5' },
      { title: 'h6', block: 'h6' }
    ] },

    { title: 'Blocks', items: [
      { title: 'p', block: 'p' },
      { title: 'div', block: 'div' },
      { title: 'pre', block: 'pre' },
    ] },

    { title: 'Containers', items: [
      { title: 'section', block: 'section', wrapper: true, merge_siblings: false },
      { title: 'article', block: 'article', wrapper: true, merge_siblings: false },
      { title: 'blockquote', block: 'blockquote', wrapper: true },
      { title: 'hgroup', block: 'hgroup', wrapper: true },
      { title: 'aside', block: 'aside', wrapper: true },
      { title: 'figure', block: 'figure', wrapper: true }
    ] }
  ],
 });
    </script>

    <div class="main-cntent"></div><br />
    <img src="{% static 'images/logo_b.png' %}" alt="thePythoneer.tech" class="float-right" style="max-width : 70%;margin-left : %"/>
    <form action="" method="post" enctype="multipart/form-data">
    <legend>Enter Data For New Blog Entry </legend>
    {% csrf_token %}
    {{ form.as_p }}
    {% comment %} <input type="text" name="title" id="title" ></input> {% endcomment %}
            <input type="submit" name="submitbtn" class="btn btn-primary btn-block" />
    {% comment %} <button name="submitbtn">Submit</button> {% endcomment %}
    <br /><br />
    </form>
    <script src="/static/js/form_style.js"></script>
{% endblock %}

blog/blog_app/templates/dash-basic.html
<!DOCTYPE html>
<html lang="en">

<!-- Static assets -->
{% load static %}

<head>
<meta charset="utf-8" />

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>
    Dashboard | thePythoneer.tech
</title>

<!--     Fonts and icons     -->
<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

<!-- CSS Files -->
<link href="{% static '/css/dashboard.css' %}" rel="stylesheet">

</head>

<body class="">
<div class="wrapper">

    {% include 'includes/sidebar.html' %}

    <div class="main-panel">

    {% include 'includes/navigation.html' %}

    <div class="content">

        {% block content %}{% endblock content %}

    </div>

    {% include 'includes/footer.html' %}

    </div>
    
</div>

{% include 'includes/scripts.html' %}

{% include 'includes/scripts-sidebar.html' %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

</body>

</html>

blog/blog_app/templates/dashboard.html
{% extends "dash-basic.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
      <div class="col-lg-4 card-title card">
        <h1>Hello</h1>
      </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

{% endblock javascripts %}